#!/bin/bash

set -ex

setup_hugepages() {
    if [ "$(cat /proc/meminfo | sed -n 's/^Hugepagesize: *//p')" != "32768 kB" ] ; then
        # octeon_cp_agent requires hugepages aligned to 4M. To achived that,
        # ensure to use 32M hugepages (via default_hugepagesz=32M boot cmdline).
        echo "WARNING: hugepage size not as expected 32M."
        cat /proc/meminfo
    fi
    if [ "$(cat /proc/sys/vm/nr_hugepages)" -lt 32 ] ; then
        echo 32 > /proc/sys/vm/nr_hugepages
    fi
    if ! mount | grep -q "^none on /dev/huge type hugetlbfs " ; then
        mkdir -p /dev/huge
        mount -t hugetlbfs none /dev/huge
    fi
}

run() {
    # from http://file.brq.redhat.com/~thaller/SDP-CP-agent.docx
    setup_hugepages

    chroot /host modprobe vfio-pci

    pem="$(lspci -d 177d:a06c -n | awk 'NR==1{print $1}')"
    rvu_pf_2="$(lspci -d 177d:a0ef -n | awk 'NR==2{print $1}')"

    test -n "$pem"
    test -n "$rvu_pf_2"

    echo vfio-pci > "/sys/bus/pci/devices/$pem/driver_override"
    echo "$pem" > /sys/bus/pci/drivers_probe

    echo vfio-pci > "/sys/bus/pci/devices/$rvu_pf_2/driver_override"
    echo "$rvu_pf_2" > /sys/bus/pci/drivers_probe

    exec /usr/bin/octep_cp_agent /usr/bin/cn106xx.cfg -- --sdp_rvu_pf "$rvu_pf_2" --pem_dev "$pem"
}

run
