#!/bin/bash

set -ex

setup_hugepages() {
    if [ "$(cat /proc/meminfo | sed -n 's/^Hugepagesize: *//p')" != "32768 kB" ] ; then
        # octeon_cp_agent requires hugepages aligned to 4M. To achived that,
        # ensure to use 32M hugepages (via default_hugepagesz=32M boot cmdline).
        echo "WARNING: hugepage size not as expected 32M."
        cat /proc/meminfo
    fi
    if [ "$(cat /proc/sys/vm/nr_hugepages)" -lt 32 ] ; then
        echo 32 > /proc/sys/vm/nr_hugepages
    fi
    if ! mount | grep -q "^none on /dev/huge type hugetlbfs " ; then
        mkdir -p /dev/huge
        mount -t hugetlbfs none /dev/huge
    fi
}

sysfs_write() {
    printf '%s\n' "$1" > "$2"
}

bind_vfio_pci() {
    sysfs_write vfio-pci "/sys/bus/pci/devices/$1/driver_override"
    if [ -f "/sys/bus/pci/devices/$1/driver/unbind" ] ; then
        sysfs_write "$1" "/sys/bus/pci/devices/$1/driver/unbind"
    fi
    sysfs_write "$1" /sys/bus/pci/drivers_probe
}

run() {
    # Follows [1].
    #
    # [1] https://github.com/MarvellEmbeddedProcessors/pcie_ep_octeon_target/blob/35c9be07d2eefe1c909efefc9faa495db965a58e/target/apps/octep_cp_agent/README#L107
    setup_hugepages

    chroot /host modprobe vfio-pci

    pem="$(lspci -d 177d:a06c -n | awk 'NR==1{print $1}')"
    dpi="$(lspci -d 177d:a080 -n | awk 'NR==1{print $1}')"
    rvu_pf_2="$(lspci -d 177d:a0ef -n | awk 'NR==2{print $1}')"

    test -n "$pem"
    test -n "$dpi"
    test -n "$rvu_pf_2"

    bind_vfio_pci "$pem"
    bind_vfio_pci "$dpi"

    exec /usr/bin/octep_cp_agent /usr/bin/cn106xx.cfg -- --sdp_rvu_pf "$rvu_pf_2" --pem_dev "$pem"
}

run
